### ISSUE TITLE
MR support

### ISSUE THREAD

**Issue by ChengranAA** [OmooLab/BioxelNodes#11]
Hi there, 
I think this is a very cool project. I have tried the guide on the MR DICOM files I have (3D raw file from the scanner). But it seems like it's not doing anything (the included example works, so probably not because of my setup) . Since I am also very new to 3D renderings, is this project also works for MRI images? And if so what kind of data would it take ? 
Thank you very much!
Best

**Comment by icrdr** [comment]
What format of your MR images? Current version of Bioxel nodes only support dcm .tif .png .jpg as vaild format, others will cancel importing. 
I am working on more support formats😉, next version will release soon

**Comment by ChengranAA** [comment]
I have .dcm files in a one file for one slice manner, I also separate one volume in a separate folder. The import seems correct. But the rendering was not shown. I am more than happy to test future versions, nifti format will be very nice!

**Comment by icrdr** [comment]
nifti format support added since v.0.1.1 
also, bioxel nodes v.0.1.1 will identify and read DICOM series id when importing, you don't need to separate series before importing 👍
