### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by forest-hermit** [OmooLab/BioxelNodes#20]
In the blender extensions web its not mentioned Linux as supported os, will it be supported in future versions? Thanks

**Comment by icrdr** [comment]
Bioxel Nodes v0.3.x is now fully support Linux, please check https://extensions.blender.org/add-ons/bioxelnodes/

**Comment by forest-hermit** [comment]
Thank you very much, sorry for doesn't reply before. Have a nice holidays.
