### ISSUE TITLE
Cylinder cutter not working

### ISSUE THREAD

**Issue by weizhuowang** [OmooLab/BioxelNodes#37]
It is my understanding that cylinder cutter should keep the content inside the cylinder volume. However I tried to cut with a cylinder but the result is that everything is gone. If I check the invert option, then nothing is cut, meaning everything is still there. Could you double check if there is a bug? I'm using Blender 4.2 on linux with BioxelNodes v0.3.2

**Comment by icrdr** [comment]
v0.3.2 passed all my tests include cylinder cutter, could you provide the .blend file (save with all assets)(top bar > Bioxel Nodes > save staged data)?
